### ISSUE TITLE
crash with laser drill turret + sewa

### ISSUE THREAD

**Issue by mccorkle** [Jimmacle/SEWebAPI#11]
On my stable branch server version 01_144_011.
Built from this repo, master, hash 381176deeb954833f689f99ff55fa5c3be55fa89, august 21st. 

Fixed it by removing pheonix's laster drill turret mod:
https://steamcommunity.com/sharedfiles/filedetails/?id=681276386

```
2016-09-06 21:58:23.543 - Thread:   1 ->  Exception occured: System.NullReferenceException: Object reference not set to an instance of an object.
   at Phoenix.LaserDrill.LaserDrillTurret.<>c.<CreateTerminalControls>b__14_1(IMyTerminalBlock b)
   at WebAPIPlugin.WebTerminalBlock..ctor(IMyTerminalBlock block, Boolean includeProperties)
   at WebAPIPlugin.BlocksHandler.<>c__DisplayClass1_0.<Get>b__0(IMyTerminalBlock x)
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at WebAPIPlugin.BlocksHandler.Get(HttpListenerContext context)
   at WebAPIPlugin.APIServer.ProcessQueue(Int32 limit)
   at WebAPIPlugin.Plugin.Update()
   at Sandbox.MySandboxGame.Update()
   at Sandbox.Engine.Platform.Game.UpdateInternal()
   at Sandbox.Engine.Platform.Game.RunSingleFrame()
   at Sandbox.Engine.Platform.FixedLoop.<>c__DisplayClass1.<Run>b__0()
   at Sandbox.Engine.Platform.GenericLoop.Run(VoidAction tickCallback)
   at Sandbox.Engine.Platform.Game.RunLoop()
   at Sandbox.MySandboxGame.Run(Boolean customRenderLoop, Action disposeSplashScreen)
   at VRage.Dedicated.DedicatedServer.RunInternal()
   at VRage.Dedicated.DedicatedServer.RunMain(String instanceName, String customPath, Boolean isService, Boolean showConsole)
   at VRage.Dedicated.DedicatedServer.ProcessArgs(String[] args)
   at VRage.Dedicated.DedicatedServer.Run[T](String[] args)
   at SpaceEngineersDedicated.MyProgram.Main(String[] args)
```

Is this something I should report to Pheonix?

**Comment by Gwindalmir** [comment]
Jimmacle reached out to me, I'm looking into this.

EDIT: Do you actually have the drill turret on the grid, or just any turret?

**Comment by mccorkle** [comment]
Thanks Pheonix!  Let me know if you need any more details to reproduce, or if you need access to my server.

**Comment by mccorkle** [comment]
@Phoenix84 I think the drill turret was on another ship.  I don't recall putting the sewa block on my drill turret ship.  I can check this evening.

**Comment by mccorkle** [comment]
@Phoenix84 Verified -- my drill ship prototype does NOT have the web api block on its grid.  The web api grid is on a distinct grid.  

sbc and sbs available here if you'd like to take a look at my save: 
https://www.dropbox.com/s/uqiev8621ux4pqf/sewa-drill-crash-save.zip?dl=0

**Comment by Gwindalmir** [comment]
I found where the issue is, I should have a fix posted soon.
I'm assuming you _do_ have a non-drill turret (eg. vanilla) or ship drill on that grid though.
That's where the problem is.

**Comment by mccorkle** [comment]
Oh yeah,  I still have the three vanilla drills on the front to right click
clear out stone in the way so that the drill turret picks up less stone.

**Comment by Gwindalmir** [comment]
I have posted a fix for the crash in the beam drill mod.
Invalid properties will appear, but that's due to a current game limitation.

**Comment by mccorkle** [comment]
Updated mod 681276386, and that sees to fix the crash.  Thank you for the fix!
