### ISSUE TITLE
Occasional bug with duplicate api keys in api.cfg

### ISSUE THREAD

**Issue by mccorkle** [Jimmacle/SEWebAPI#12]
After running a dedicated server for multiple days, sometimes I'll stop the restart to let it update mods and load it back and this an immediate crash to desktop for seds.  This is in my logs:

```
2016-09-13 23:53:50.760 - Thread:   1 ->  MySandboxGame.Initialize() - END
2016-09-13 23:53:50.760 - Thread:   1 ->  SEWA: Initializing SE Web API
2016-09-13 23:53:50.765 - Thread:   1 ->  Exception occured: System.ArgumentException: An item with the same key has already been added.
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at WebAPIPlugin.APIBlockCache.Load()
   at WebAPIPlugin.Plugin.Init(Object obj)
   at Sandbox.MySandboxGame.Run(Boolean customRenderLoop, Action disposeSplashScreen)
   at VRage.Dedicated.DedicatedServer.RunInternal()
   at VRage.Dedicated.DedicatedServer.RunMain(String instanceName, String customPath, Boolean isService, Boolean showConsole)
   at VRage.Dedicated.DedicatedServer.ProcessArgs(String[] args)
   at VRage.Dedicated.DedicatedServer.Run[T](String[] args)
   at SpaceEngineersDedicated.MyProgram.Main(String[] args)
2016-09-13 23:53:50.766 - Thread:   1 ->  Hiding window
2016-09-13 23:53:50.975 - Thread:   1 ->  Network readers disposed
2016-09-13 23:53:50.980 - Thread:   1 ->  Logging off Steam...
2016-09-13 23:53:50.981 - Thread:   1 ->  Shutting down server...
2016-09-13 23:53:51.033 - Thread:   1 ->  Done
```

All I have to do to fix it is open up api.cfg and remove the duplicate API key from it, then restart my SEDS.

**Comment by mccorkle** [comment]
I did reproduce this two days ago.  Still not sure how it happens, but there was two copies of a key seems to be random, but the duplicate is always the last line.  This time there was a newline before the duplicate.

**Comment by Jimmacle** [comment]
Closing because new ModAPI features eliminate the need for the config file
