### ISSUE TITLE
NullReferenceException with dev build 01_165_005

### ISSUE THREAD

**Issue by mccorkle** [Jimmacle/SEWebAPI#14]
Just got this on my dev server.  I can revert to stable for the time being, but I wanted to share it with you.  

```
2016-12-08 18:49:41.506 - Thread:   1 ->  Exception occured: System.NullReferenceException: Object reference not set to an instance of an object.
   at WebAPIPlugin.Plugin.Init(Object obj)
   at Sandbox.MySandboxGame.Run(Boolean customRenderLoop, Action disposeSplashScreen)
   at VRage.Dedicated.DedicatedServer.RunInternal()
   at VRage.Dedicated.DedicatedServer.RunMain(String instanceName, String customPath, Boolean isService, Boolean showConsole)
   at VRage.Dedicated.DedicatedServer.ProcessArgs(String[] args)
   at VRage.Dedicated.DedicatedServer.Run[T](String[] args)
   at SpaceEngineersDedicated.MyProgram.Main(String[] args)
```

**Comment by Jimmacle** [comment]
I'll take a look today, Keen probably changed something goofy. The whole thing will probably need to get some work done to make it thread-safe now that entities are initialized in parallel and I want to look into some other solutions to make adding functionality to the API easier.

**Comment by mccorkle** [comment]
I haven't seen this error since then (though I haven't been actively using the interface either) -- so lets close this until I reproduce it.
